// todo page
export const todoItemMove = {
  TODO_ITEM_MOVE__SET_NEW_TODO_ITEM: 'TODO_ITEM_MOVE__SET_NEW_TODO_ITEM',
  TODO_ITEM_MOVE__SET_NULL_TODO_ITEM: 'TODO_ITEM_MOVE__SET_NULL_TODO_ITEM'

}

export const todoLists = {
  // TODOS_LISTS__INSERT_ONE_TODO_ITEM: 'TODOS_LISTS__INSERT_ONE_TODO_ITEM',
  inserts: {
    TODOS_LISTS__INSERT_ONE_TODO_ITEM__REQUEST: 'TODOS_LISTS__INSERT_ONE_TODO_ITEM__REQUEST',
    TODOS_LISTS__INSERT_ONE_TODO_ITEM__SUCCESS: 'TODOS_LISTS__INSERT_ONE_TODO_ITEM__SUCCESS',
    TODOS_LISTS__INSERT_ONE_TODO_ITEM__FAILURE: 'TODOS_LISTS__INSERT_ONE_TODO_ITEM__FAILURE'
  },
  updates: {
    TODOS_LISTS__UPDATE_TODO_ITEM_BY_ID__SUCCESS: 'TODOS_LISTS__UPDATE_TODO_ITEM_BY_ID__SUCCESS',
    TODOS_LISTS__UPDATE_TODO_ITEM_BY_ID__REQUEST: 'TODOS_LISTS__UPDATE_TODO_ITEM_BY_ID__REQUEST',
    TODOS_LISTS__UPDATE_TODO_ITEM_BY_ID__FAILURE: 'TODOS_LISTS__UPDATE_TODO_ITEM_BY_ID__FAILURE'
  },
  deletes: {
    TODOS_LISTS__DELETE_ONE_TODO_ITEM_BY_TODO_ITEM_ID__REQUEST: 'TODOS_LISTS__DELETE_ONE_TODO_ITEM_BY_TODO_ITEM_ID__REQUEST',
    TODOS_LISTS__DELETE_ONE_TODO_ITEM_BY_TODO_ITEM_ID__SUCCESS: 'TODOS_LISTS__DELETE_ONE_TODO_ITEM_BY_TODO_ITEM_ID__SUCCESS',
    TODOS_LISTS__DELETE_ONE_TODO_ITEM_BY_TODO_ITEM_ID__FAILURE: 'TODOS_LISTS__DELETE_ONE_TODO_ITEM_BY_TODO_ITEM_ID__FAILURE'
  },
  finds: {
    TODO_LIST__FIND_ALL_TODO_ITEMS__REQUEST: 'TODO_LIST__FIND_ALL_TODO_ITEMS__REQUEST',
    TODO_LIST__FIND_ALL_TODO_ITEMS__SUCCESS: 'TODO_LIST__FIND_ALL_TODO_ITEMS__SUCCESS',
    TODO_LIST__FIND_ALL_TODO_ITEMS__FAILURE: 'TODO_LIST__FIND_ALL_TODO_ITEMS__FAILURE'
  }
}
