// todo page
export const todoItemMove = {
  TODO_ITEM_MOVE__SET_NEW_TODO_ITEM: 'TODO_ITEM_MOVE__SET_NEW_TODO_ITEM',
  TODO_ITEM_MOVE__SET_NULL_TODO_ITEM: 'TODO_ITEM_MOVE__SET_NULL_TODO_ITEM'

}

export const todoLists = {
  TODOS_LISTS__INSERT_ONE_TODO_ITEM: 'TODOS_LISTS__INSERT_ONE_TODO_ITEM',
  TODOS_LISTS__UPDATE_TODO_ITEM_BY_TODO_AREA_ID: 'TODOS_LISTS__UPDATE_TODO_ITEM_BY_TODO_AREA_ID',
  TODOS_LISTS__UPDATE_TODO_ITEM_BY_ID: 'TODOS_LISTS__UPDATE_TODO_ITEM_BY_ID',
  TODOS_LISTS__REMOVE_ONE_TODO_ITEM_BY_TODO_AREA_ID_AND_TODO_ITEM_ID: 'TODOS_LISTS__REMOVE_ONE_TODO_ITEM_BY_TODO_AREA_ID_AND_TODO_ITEM_ID'
}
