export const TODO_ITEM_MOVE__ONDRAG_START = 'TODO_ITEM_MOVE__ONDRAG_START'
export const TODO_ITEM_MOVE__ONDRAG_END = 'TODO_ITEM_MOVE__ONDRAG_END'

export const TODOS_LISTS__ONDROP = 'TODOS_LISTS__ONDROP'